name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.2.0b3"

      - name: Install dependencies
        run: poetry install

      - name: Run linting checks
        run: poetry run make check

      - name: Run tests (coverage)
        run: |
          poetry run make test
          poetry run make coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
