---
name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: 3.10

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 3.10

      - name: Install dependencies
        run: poetry install

      - name: Build package & docs
        run: poetry build

      - name: Publish
        run: poetry publish -u {{ secrets.USERNAME }} -p {{ secrets.PASSWORD }}
